(function(g){var window=this;'use strict';var Peb=function(a,b,c){var d;g.J(function(e){switch(e.j){case 1:var f=b;a.W.L("web_player_pt_tt")?(f=g.cr(f).exp||"",f=f.includes("xpv")||f.includes("xpe")):f=!1;if(!f){e.Fa(2);break}if(a.videoData.yw){e.Fa(3);break}g.wa(e,4);return g.F(e,a.D.promise,6);case 6:g.xa(e,3);break;case 4:return g.ya(e),e.return();case 3:d={potc:"1",pot:a.videoData.yw},b=g.dr(b,d);case 2:a.j=g.xr(b,c),g.va(e)}})},l3=function(a){a.isActive()||a.start()},Qeb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},
Reb=function(a,b){var c=new g.sP;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Seb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.F(f,g.Zt(),2);if(f.j!=3){d=f.B;if(!d)throw g.vt("gct");return g.F(f,g.KP(d),3)}e=f.B;return f.return(e.get("captions",c))})},Teb=function(a,b,c){Seb(a,b).then(function(d){d&&c(d.trackData,new g.sP(d.metadata))})},Web=function(a){if(!Ueb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(Veb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Xeb=function(){return g.Hs("yt-player-caption-display-settings")},m3=function(){this.segments=[]},Yeb=function(a,b){var c=g.ec(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Vb(a.segments,c),g.Vb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.bc(a.segments,c,0,b),g.bc(a.segments,c+1,0,b)))},Zeb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.oa=c;this.Z=d;this.G=e;this.Y=f;this.D=new m3;this.K=-1;this.C=this.B=this.j=null;this.N=new g.Yo(this.A_,1E3,this);this.events=new g.AE(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.PB);this.PB();this.A_()},$eb=function(a){return a.j&&a.j.Rf?a.j.Rf+a.player.Ac()<a.player.getCurrentTime():!1},afb=function(a,b){if(a.policy.xm&&a.player.fu()){var c=g.XM(b,a.policy,{});
c.set("pot",a.player.fu());c=c.Ce()}else c=g.XM(b,a.policy,{}).Ce();var d={format:"RAW",withCredentials:!0};if(a.policy.Ma){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.BK(e,g.iL):d.postBody=(0,g.LT)([120,0])}a.G&&(d.responseType="arraybuffer");a.C=g.Br(c,d,3,100).then(function(f){a:{f=f.xhr;a.Ka();if(a.B){var h=!(a.G?f.response:f.responseText)||f.status>=400,l=g.jIa(f);if(l){f=g.XM(a.B,a.policy,{});a.B.Ol(f,l);afb(a,a.B);break a}h?a.player.ma("capfail",{status:f.status}):(a.player.Lh().jg("fcb_r"),
l=a.B.gb[0].Oa,a.Z!=null&&a.K!==l&&(h=a.B.gb[0],a.G?a.Z(f.response,(h.startTime+a.player.Ac())*1E3):a.Z(f.responseText,(h.startTime+a.player.Ac())*1E3),a.K=l))}a.B=null;a.C=null}}).fl(function(f){a.B=null;
a.C=null;var h;a.player.ma("capfail",{status:(h=f.xhr)==null?void 0:h.status})});
a.B=b;Yeb(a.D,a.B.gb[0].Oa)},n3=function(a,b){g.ZX.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.K=!1;this.N=g.vC(this.J.U())&&!this.j.isManifestless},cfb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.p_a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Qcb.get(e);q==null&&(q=bfb[e]||bfb[e.replace(/-/g,"_")],g.Qcb.set(e,q));h=q||h}c.push(new g.sP({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
dfb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},efb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.p_a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},ffb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.bdb?g.bdb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={mG:c.mG};c.mG=d;var e=function(f){return function(){return String(a[f.mG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.mG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.mG,"gi"),e)}return b},o3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Pe);a.params.Pe&&Object.assign(r,a.params.Pe);Object.assign(r,c.Pe);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Pe=r;var t=q.Ui===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,B,C;(l=l.eb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(B=y.captions)==null?void 0:(C=B.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":ffb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var G=
this;this.K=[];this.Ga=!1;this.B=a;this.Ma=this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.wc=c;this.qa=b;this.D=this.Ea("captions-text");this.Nb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ua=gfb(d,e,f,h);this.vc=m;l&&(this.G=this.Ea("caption-edit"),this.T(this.G,"click",function(){G.vc()}));
this.type=0;this.Xa=this.Ua*hfb(r);this.Cb=p;a=new g.zX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.c7,this);a.subscribe("dragmove",this.b7,this);a.subscribe("dragend",this.a7,this);this.fb=this.Wa=this.rb=this.qb=0;a="";this.j.windowOpacity&&(a=Web(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":ifb[this.j.textAlign]};this.Nb&&(b["border-radius"]=a?this.Xa/8+"px":"");(this.C=
this.B.params.Ui===2||this.B.params.Ui===3)&&jfb(this,this.element);g.mm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Km){case 0:case 1:case 2:g.fp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.fp(this.element,"ytp-caption-window-bottom")}},jfb=function(a,b){var c="vertical-rl";
a.j.HU===1&&(c="vertical-lr");g.om&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.mm(b,"-o-writing-mode",c);g.mm(b,"-webkit-writing-mode",c);g.mm(b,"writing-mode",c);g.mm(b,"text-orientation","upright");g.fp(b,"ytp-vertical-caption");a.B.params.Ui===3&&(g.mm(b,"text-orientation",""),g.mm(b,"transform","rotate(180deg)"))},hfb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},kfb=function(a,b){var c={},d=b.background?b.background:a.j.Pe.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Pe.backgroundOpacity;d=Web(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Nb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Xa/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Ua*hfb(b)+"px";d=1;e=b.color||a.j.Pe.color;if(b.color||b.textOpacity!=null)e=Web(e),d=b.textOpacity==null?a.j.Pe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.bP&&(h=e=b.bP);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Pr()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Pe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.s$&&(c.visibility="hidden");b.GZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.eP||g.tt,a.B.params.Ui===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.tp===1||b.tp===2||b.tp===3||b.tp===4||b.tp===5)if(g.eP)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.tp){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},p3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},lfb=function(a){a.N=g.ne("SPAN");
g.mm(a.N,{display:"block"});g.fp(a.N,"caption-visual-line");a.D.appendChild(a.N)},mfb=function(a,b){var c=g.ne("SPAN");
g.mm(c,{display:"inline-block","white-space":"pre-wrap"});g.mm(c,kfb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.mm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.mm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},nfb=function(a,b,c){a.Ga=a.Ga||!!c;
var d={};Object.assign(d,a.j.Pe);Object.assign(d,c||b.j);Object.assign(d,a.wc.Pe);(c=!a.N)&&lfb(a);for(var e=a.Ja&&a.Ma&&g.Jc(d,a.Ma)?a.Ja:mfb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(lfb(a),e=mfb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.oe(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.eP||!g.pm(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.pm(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.tc?g.mm(e,m,"1em"):g.mm(e,m,"0.5em")))}a.Ma=d;a.Ja=e;a.K.push(b)},gfb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},pfb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new ofb(this);this.G=new ofb(this);this.j=[];this.clear()},Ifb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{Qw:a,
Jt:b,result:0};a=qfb[a];b=qfb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.oe()&&c.Jt===d;if(d)return{Qw:a,Jt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{Qw:a,Jt:b,result:2};return{Qw:a,Jt:b,result:3}},Kfb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Jfb(a.D,b,c,d))},Lfb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?Kfb(a,d.JX,d.KX,b):d.type===1&&a.B&496&&Jfb(a.G,d.JX,d.KX,b);a.j.length=0},q3=function(){this.type=0},r3=function(){this.state=this.Jt=this.Qw=0},Mfb=function(){this.timestamp=this.j=0},s3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new q3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Mfb}},t3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Rfb=function(a,b){switch(a){case 0:return Nfb[(b&127)-32];
case 1:return Ofb[b&15];case 2:return Pfb[b&31];case 3:return Qfb[b&31]}return 0},u3=function(a){return a.B[a.row][a.col]},v3=function(a,b,c){b>=2&&a.col>1&&(--a.col,u3(a).j=0);
var d=u3(a);d.timestamp=a.D.time+0;d.j=Rfb(b,c);a.col<32&&a.col++},Sfb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},w3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},Tfb=function(a){a.row=a.j>0?a.j:1;
a.col=1;w3(a,0,15)},Ufb=function(a){this.C=a;
this.G=0;this.style=new q3;this.K=new s3(this.C);this.N=new s3(this.C);this.text=new s3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Vfb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(t3(d,c),Tfb(a.B),Tfb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(t3(d,c),w3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Wfb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Xfb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},ofb=function(a){this.j=a;
this.G=0;this.C=new Ufb(this.j);this.K=new Ufb(this.j);this.B=new r3;this.D=this.C},Jfb=function(a,b,c,d){a.B.update();
b=Ifb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Qw;c=b.Jt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&v3(a,0,b),c&96&&v3(a,0,c),b!==0&&c!==0&&a.style.type===3&&t3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Qw=e,b.Jt=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Sfb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));w3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:v3(b.j,0,32);break a;case 48:c===57?(d=b.j,u3(d).j=0,d.col<32&&d.col++):v3(b.j,1,c&15)}break;case 2:c&32&&v3(b.j,2,c&31);break;case 3:c&32&&v3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:Wfb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,u3(d).j=0);break;case 36:d=b.j;b=u3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:Vfb(b,2,d);break;case 38:Vfb(b,3,d);break;case 39:Vfb(b,4,d);break;case 40:v3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Tfb(d);Xfb(b);break;case 43:Xfb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:t3(a,
d)}w3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;t3(a,d);Sfb(a,b,b+1,a.j-1);w3(a,a.row,1)}break;case 46:w3(b.D,0,15);break;case 47:t3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Wfb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},Yfb=function(){},x3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.$C.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},$fb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.hg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Zfb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new x3(a,b,e,c,l,d,m)}switch(m.hg){case 9:case 10:m.tp=1;break;case 11:m.tp=2;break;case 12:m.tp=3;break;case 13:m.tp=4;break;case 14:m.tp=5}return new x3(a,b,e,c,l.textContent||"",d,m)},Zfb=function(a,b,c,d,e){var f=g.Pr(),h=
f?g.ne("DIV"):g.ne("RUBY"),l=g.ne("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.ne("DIV"):g.ne("RP");a.textContent=b;h.appendChild(a);b=f?g.ne("DIV"):g.ne("RT");b.textContent=c;h.appendChild(b);c=e.hg;if(c===10||c===11||c===12||c===13||c===14)if(g.mm(b,"text-emphasis-style","filled circle"),g.mm(b,"text-emphasis-color","currentcolor"),g.mm(b,"webkit-text-emphasis","filled circle"),e.hg===11||e.hg===13)g.mm(b,"webkit-text-emphasis-position","under left"),g.mm(b,"text-emphasis-position","under left");c=!0;if(e.hg===4||e.hg===7||e.hg===12||
e.hg===14)g.mm(h,"ruby-position","over"),g.mm(h,"-webkit-ruby-position","before");else if(e.hg===5||e.hg===6||e.hg===11||e.hg===13)g.mm(h,"ruby-position","under"),g.mm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.ne("DIV"):g.ne("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.mm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.mm(f,"display","none"),f=f.nextElementSibling,g.mm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.mm(h.lastElementChild,"display","none"),d?(g.mm(h,"padding-top","0.6em"),g.mm(f,"top","0")):(g.mm(h,"padding-bottom","0.6em"),g.mm(f,"bottom","0")));return h},y3=function(){g.O.apply(this,arguments)},z3=function(a,b,c,d,e){g.$C.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},agb=function(a){var b="_"+A3++;
return new z3(0,0x8000000000000,0,b,a)},B3=function(a){y3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+A3++;this.K={};this.B=this.j=null;this.G=!0},C3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},D3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},E3=function(a,b){a=C3(a,b);
return a!==void 0?a:null},G3=function(a,b){a=a.getAttribute(b);
if(a!=null)return F3.test(a),a},bgb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=E3(b,"mh");a!=null&&(c.DB=a);a=E3(b,"ju");a!=null&&(c.textAlign=a);a=E3(b,"pd");a!=null&&(c.Ui=a);a=E3(b,"sd");a!=null&&(c.HU=a);a=G3(b,"wfc");a!=null&&(c.windowColor=a);b=C3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},cgb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=E3(b,"ap");a!=null&&(c.Km=a);a=C3(b,"cc");a!=null&&(c.Mt=a);a=C3(b,"ah");a!=null&&(c.Jk=a);a=C3(b,"rc");a!=null&&(c.Os=a);b=C3(b,"av");b!=null&&(c.xp=b);return c},dgb=function(a,b,c,d){var e={};
Object.assign(e,cgb(a,b));Object.assign(e,bgb(a,b));d?g.Jc(e,a.C)?(d=a.D,e=a.C):d="_"+A3++:d=b.getAttribute("id")||"_"+A3++;a=C3(b,"t")+c;b=C3(b,"d")||0x8000000000000;if(e.Ui===2||e.Ui===3)c=e.Os,e.Os=e.Mt,e.Mt=c;return new z3(a,b,0,d,e)},H3=function(a){y3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},I3=function(a){a=g.Hd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},egb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Os=a);b=b.ccColCount;b!==void 0&&(f.Mt=b);if(f.Ui===2||f.Ui===3)b=f.Os,f.Os=f.Mt,f.Mt=b;return new z3(c,d,0,e,f)},J3=function(a,b,c,d){g.ZX.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ta=d;this.G=b.uw},K3=function(a,b,c,d,e,f,h,l,m,n){o3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},L3=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},M3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},N3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},O3=function(a,b){y3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new pfb;this.j.B=1<<this.track},ggb=function(a){if(typeof a==="string")return!1;
a=new L3(a,8,0);return fgb(a)},fgb=function(a){if(!(a.byteOffset<a.j.byteLength)||N3(a)!==1380139777)return!1;
a.version=M3(a);if(a.version>1)return!1;M3(a);M3(a);M3(a);return!0},P3=function(a,b,c,d,e,f,h,l,m,n){o3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ba=[];this.oa=this.Y=this.Qa=0;this.Da=NaN;this.Hb=0;this.Sb=null;this.Va=new g.Yo(this.tca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.zX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.fp(this.element,"ytp-caption-window-rollup");g.P(this,this.Va);g.mm(this.element,"overflow","hidden")},hgb=function(a,b){if(!b)return"";
a.C&&a.B.params.HU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},igb=function(a){a.Ba=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Os,c=0,d=0,e=a.Ba.length-1;c<b&&e>-1;){var f=a.Ba[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Da)&&((d=a.j.Mt)?(e=g.ne("SPAN"),g.ue(e,"\u2013".repeat(d)),g.mm(e,kfb(a,a.j.Pe)),a.D.appendChild(e),a.Da=e.offsetWidth,a.D.removeChild(e)):a.Da=0);d=a.D;a.oa=c.call(b,a.Da,a.Hb,(a.C?d.offsetHeight:d.offsetWidth)+1)},jgb=function(a,b){igb(a);
var c=a.Ba.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Qa){var d=c>0&&a.Qa===0,e=c<a.Qa;b||isNaN(c)||d||!e||(g.fp(a.element,"ytp-rollup-mode"),g.Zo(a.Va));g.mm(a.D,"transform",hgb(a,c));a.Qa=c}igb(a)},Q3=function(){y3.call(this)},kgb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new x3(b,c,d,e.id,p.nodeValue,f||n>0,g.Hc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);kgb(a,b,c,d,e,!0,p,q,m)}}},lgb=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},mgb=function(a,b,c,d){d=Object.assign({DB:0},d);
return new z3(a,b,c,"_"+A3++,d)},R3=function(a,b){g.O.call(this);
this.J=a;this.W=b;this.j=null;this.B=this.J.FA()},ngb=function(a){if(typeof a==="string"||ggb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.bM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.fK(a)},pgb=function(a,b,c){if(typeof b==="string"||ggb(b))return[{trackData:b,
BU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.hEa(d);if(a.B&&e){var f=g.$Da(e),h=g.aEa(e);e=e.rj;f&&e&&a.B.rI(e,f,h)}a=g.kM(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.fK(e),f.push({trackData:e,BU:c+h*1E3});ogb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},ogb=function(a,b,c){var d=g.bM(a,0,1836476516),e=9E4;
d&&(e=g.cM(d)||9E4);d=0;for(var f=g.kM(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.bM(a,l.dataOffset,1953653094))&&(l=g.bM(a,l.dataOffset,1952867444))&&(l=g.iM(l)/e*1E3,h===0&&(d=l),b[h].BU=l-d+c||c*h*1E3)}},qgb=function(a,b,c,d,e){if(!ggb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new O3(e,b));return a.j.gp(c,d)},rgb=function(a,b,c){a.j||(a.j=new Q3);
a=a.j.gp(b,c);Math.random()<.01&&g.Hw(Error("Deprecated subtitles format in web player: WebVTT"));return a},tgb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new H3(sgb(b))),a.j.gp(c,d)}catch(f){return g.Gw(f),[]}var e=g.d1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new B3(sgb(b),a.W)),a.j.gp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},sgb=function(a){var b=
{};
if(a=g.vP(a))b.lang=a,g.pab.test(a)&&(b.Ui=1);return b},S3=function(a){g.WX.call(this,a);
var b=this;this.J=a;this.W=this.J.U();this.videoData=this.J.getVideoData();this.rb=this.J.ob();var c;this.fb=(c=this.J.getVideoData(1))==null?void 0:g.jQ(c);this.C={Pe:{}};this.G={Pe:{}};this.Ga=[];this.Ba={};this.Ua={};this.N=!1;this.Nb=g.YQ(this.videoData);this.Wa=g.q_a(this.videoData,this.J);this.Hb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.ye;this.Va=this.W.controlsType==="3";this.j=this.Z=this.Y=this.Qa=this.qb=null;this.Xa=new R3(this.J,this.W);this.B=null;this.oa=new g.AE(this);
this.K=new g.T({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Ip("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.zp(d));this.storage=c;var e;this.Kb=!((e=a.Be())==null||!e.iI());this.D=ugb(this);this.Da=!this.D&&this.Va&&this.Kb&&this.Wa;g.P(this,this.Xa);this.D?this.Ma=this.Ja=null:(this.Ja=new g.Xo(this.TU,void 0,this),g.P(this,this.Ja),this.Ma=new g.Yo(this.Zda,2E3,this),g.P(this,
this.Ma));g.P(this,this.oa);g.GR(this.player,this.K.element,4);g.P(this,this.K);this.oa.T(a,"contentPoTokenReady",this.MG);this.D||this.oa.T(a,"resize",this.UU);(this.Cb=g.MO(this.W)&&!g.ps()&&!this.J.isFullscreen()&&!this.D&&!this.Da)&&this.oa.T(a,"resize",this.Cba);this.oa.T(a,"onPlaybackAudioChange",this.Oaa);this.oa.T(a,g.bD("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.cD("captions"),function(f){b.onCueRangeExit(f)});
this.fb&&this.oa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
vgb(this,Xeb()||{});this.player.yd("onCaptionsModuleAvailable")},ygb=function(a){if(a.W.Kb===1||a.videoData.hD===1||g.EQ(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.W.Kb===2){if(g.bP(a.W))var c=wgb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=Qeb(a.player.getAudioTrack(),g.bP(a.W));var d=g.EQ(a.videoData,"yt:cc");if(xgb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.EQ(a.videoData,
"yt:cc")==="on"},T3=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},xgb=function(a){var b=void 0,c=g.Os(g.Ns(),65);
if(g.bP(a.W)&&c!=null){if(wgb(a)!=null)return!1;b=!c}return b},zgb=function(a){var b;
a.Nb?b=new J3(a.W,a.videoData,a.getAudioTrack(),a.player):a.Wa?b=new n3(a.videoData.j,a.player):a.Hb?b=new g.$X(a.W,a.videoData,a.getAudioTrack()):b=new g.aY(a.W,a.videoData.ye,a.videoData.videoId,g.hMa(a.videoData),a.videoData.Kn,a.videoData.eventId);return b},V3=function(a,b){if(a.j){if(a.Z&&a.Z.D)return a.Z.D;
g.RQ(a.videoData)&&(b=!0);b||(b=a.Sb?!1:a.Hb?!1:!0);b=b||Agb(a);b=g.XX(a.j.B,b);var c=null;if(g.bP(a.W)){var d=a.J.isInline()?void 0:g.Hs("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.EQ(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.vP(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.vP(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.EQ(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.vP(b[f])===d[e])return b[f];d=null;a.Z&&a.Z.C&&(d=a.Z.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||U3(a));d&&c&&g.vP(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Reb(d,c));return d}return null},U3=function(a){return a.Z&&a.Z.j},W3=function(a){var b=U3(a);
return!!b&&a.B===b},Bgb=function(a){var b=Qeb(a.player.getAudioTrack(),g.bP(a.W)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=V3(a,a.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&T3(a)?c=U3(a):xgb(a)||a.N||ygb(a)?c=V3(a,a.N):T3(a)&&(c=U3(a));if(a.D||a.Da){var d=g.XX(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.ne("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.tP(f));h.setAttribute("srclang",g.vP(f));h.setAttribute("id",f.toString());a.Da||h.setAttribute("src",a.j.yx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Be();c.yE(b);c=
c.Jb();a.Kb&&a.oa.T(c.textTracks,"change",a.bda)}else!a.B&&c&&X3(a,c),a.player.yd("onCaptionsTrackListChanged"),a.player.qf("onApiChange")},Cgb=function(a,b){var c=a.J.Be().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},X3=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.N=c,a.N&&(g.bP(a.W)?Y3(a,!!b):Z3(a,!!b)));a.W.L("html5_report_caption_format_change")&&Dgb(a,a.B,b,a.N,!1);a.B=b;T3(a)&&(b=U3(a),a.W.L("html5_report_caption_format_change")&&Dgb(a,a.B,b,a.N,!0),a.B=b);var d;Egb(a,(d=a.B)!=null?d:void 0);a.load()},Ggb=function(a,b){if(b instanceof z3){var c=a.Ba[b.id];
c&&c.B!==b&&(c.dispose(),delete a.Ba[b.id],c=null);c||(c=Fgb(a,b))&&(a.Ba[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},Fgb=function(a,b){var c=Hgb(a);
if(!c)return null;var d=a.B?g.vP(a.B):null;d&&g.pab.test(d)&&(b.params.Ui=1);var e=a.rb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.W.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.DB!=null?b.params.DB:b.j.length>1?1:0){case 1:return new K3(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.HN.bind(a),a.J);case 2:return new P3(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.HN.bind(a),a.J);default:return new o3(b,a.C,a.G,c.width,c.height,e,
d,a.W.experiments,a.HN.bind(a),a.J)}},vgb=function(a,b,c){c=c===void 0?!1:c;
var d=$3.Pe;a.C={};Object.assign(a.C,$3);a.C.Pe={};Object.assign(a.C.Pe,d);a.G={Pe:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;F3.test(f);e.Pe.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;F3.test(f);e.Pe.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||$3.windowColor;F3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Pe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Pe.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Pe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Pe.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=$3.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Pe.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Pe.fontFamily=f;a.loaded&&a.UU();c&&g.Gs("yt-player-caption-display-settings",b,2592E3)},Jgb=function(a,b,c){b&&!a.Y?(b=agb({Ui:0,
lang:"en"}),a.Y=[b,new x3(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.kf(a.Y)):!b&&a.Y&&(Igb(a,a.Y),a.Y=null)},Igb=function(a,b){a.player.qp(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Wb(a.Ga,c.value);l3(a.Ja)},Egb=function(a,b){a.W.L("html5_modify_caption_vss_logging")&&(a.videoData.aE=b)},Hgb=function(a){var b=a.rb.getVideoContentRect(!0).height,c=a.rb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},Z3=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Y3=function(a,b){a.J.isInline()||g.Gs("yt-player-sticky-caption",b,2592E3)},wgb=function(a){if(!a.J.isInline())return g.Hs("yt-player-sticky-caption")},ugb=function(a){var b,c=!((b=a.J.Be())==null||!b.hI());
return a.Va&&c&&!a.Wa},Agb=function(a){return a.W.L("web_deprecate_always_includes_asr_setting")&&g.bP(a.W)?!0:!!g.Os(g.Ns(),66)},Dgb=function(a,b,c,d,e){e?a.pj(c,!0,"g"):d?b?a.pj(c,!!c,"m"):c&&a.pj(c,!0,"m"):!b&&c&&a.pj(c,!0,"s")};
g.ZX.prototype.nT=g.da(54,function(){return!1});
g.ZX.prototype.Lu=g.da(53,function(){});
g.$X.prototype.Lu=g.da(52,function(a,b,c){var d=this;this.Ka();b=this.yx(a,b);this.nt();Peb(this,b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.aY.prototype.Lu=g.da(51,function(a,b,c){var d=this;this.Ka();b=this.yx(a,b);this.nt();this.j=g.xr(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.HX.prototype.aA=g.da(50,function(){for(var a=g.fe(document,"track",void 0,this.j),b=0;b<a.length;b++)g.se(a[b])});
g.a_.prototype.aA=g.da(49,function(){this.mediaElement.aA()});
g.HX.prototype.iI=g.da(48,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.a_.prototype.iI=g.da(47,function(){return this.mediaElement.iI()});
g.HX.prototype.hI=g.da(46,function(){return!!this.j.textTracks});
g.a_.prototype.hI=g.da(45,function(){return this.mediaElement.hI()});
g.HX.prototype.yE=g.da(44,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.a_.prototype.yE=g.da(43,function(a){this.mediaElement.yE(a)});
g.IV.prototype.rI=g.da(39,function(a,b,c){this.Yc.rI(a,b,c)});
g.j_.prototype.rI=g.da(38,function(a,b,c){this.Ja.set(a,{Rt:b,Pz:c})});
g.IV.prototype.zF=g.da(37,function(a){return this.Yc.zF(a)});
g.j_.prototype.zF=g.da(36,function(a){var b=2;this.K.has(a)?b=0:g.X4a(this,a)&&(b=1);return b});
g.yR.prototype.Tj=g.da(34,function(a,b){var c=g.qR(this.app);c&&c.Tj(a,b)});
g.$V.prototype.Tj=g.da(33,function(a,b){a=[a,b];g.ZV(this,g.ZI(this.provider),"cfi",a)});
g.nW.prototype.Tj=g.da(32,function(a,b){this.qoe&&this.qoe.Tj(a,b)});
g.OW.prototype.Tj=g.da(31,function(a,b){this.Vb().Tj(a,b)});
g.yR.prototype.pj=g.da(30,function(a,b,c){var d=g.qR(this.app);d&&d.pj(a,b,c)});
g.$V.prototype.pj=g.da(29,function(a,b,c){b=[a,b,this.Hb,c];g.ZV(this,g.ZI(this.provider),"cfs",b);this.Hb=a});
g.nW.prototype.pj=g.da(28,function(a,b,c){this.qoe&&this.qoe.pj(a,b,c)});
g.OW.prototype.pj=g.da(27,function(a,b,c){this.Vb().pj(a,b,c)});
g.EV.prototype.MF=g.da(18,function(){return this.N});
g.I_.prototype.MF=g.da(17,function(){var a;return((a=g.qR(this))==null?void 0:a.FA())||null});
g.yR.prototype.FA=g.da(16,function(){return this.app.MF()});
g.OW.prototype.FA=g.da(15,function(){var a;return((a=this.ra)==null?void 0:a.MF())||null});
g.OL.prototype.AK=g.da(1,function(a){return(a=this.uo(a))?a.j:0});
g.mN.prototype.AK=g.da(0,function(){return 0});
var Veb=/#(.)(.)(.)/,Ueb=/^#(?:[0-9a-f]{3}){1,2}$/i,bfb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
m3.prototype.contains=function(a){a=g.ec(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
m3.prototype.length=function(){return this.segments.length/2};
g.z(Zeb,g.O);g.k=Zeb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.PB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ac();var b=this.j;this.j=g.Qb(this.oa.Xr(a).gb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new m3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.A_=function(){this.Ka();var a;if(a=this.j!=null)a=this.j,a=a.j.Ct(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.ID(a);var b=a.gb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.FA()){var d=b.j.info.id,e=b.Oa,f=a.gb[0].Ve;if(this.policy.Ma){if(c=c.DK(f,e,d,3))a.D=c}else if(d=c.wA(f,e,d,3))if(c=c.zF(e),c===0)d&&(a.j=new g.GL(d));else if(c===2){this.N.start();$eb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Jo(b.Oa)?(this.D.contains(a.gb[0].Oa)||afb(this,a),this.j=g.Qb(a.gb)):$eb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(n3,g.ZX);g.k=n3.prototype;g.k.Lu=function(a,b,c){var d=this;this.nt();b=dfb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?efb(this,b,"386"):efb(this,b));if(b){var e=(b.index.AK(b.index.zo())-b.index.getStartTime(b.index.zo()))*1E3,f=new g.UQa(this.W),h=function(){d.C&&d.C.reset();d.K=!0};
this.W.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Zeb(f,this.J,b,function(l,m){c(l,a,m,e)},this.N||g.OE(b.info),h)}};
g.k.nT=function(){var a=this.K;this.K=!1;return a};
g.k.qB=function(a){var b=this.N?[new g.sP({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.sP({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?cfb(this,"386"):cfb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.YX(this.B,c.value);a()};
g.k.nt=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.yx=function(){return""};
var F3=/^#(?:[0-9a-f]{3}){1,2}$/i;var ifb=["left","right","center","justify"];g.z(o3,g.T);g.k=o3.prototype;g.k.c7=function(a,b){this.Wa=a;this.fb=b;var c=g.wm(this.element,this.element.parentElement);this.qb=a-c.x;this.rb=b-c.y};
g.k.b7=function(a,b){if(a!==this.Wa||b!==this.fb){g.ep(this.element,"ytp-dragging")||g.fp(this.element,"ytp-dragging");var c=g.ym(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.rb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Hd(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Hd(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.Hd(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.Hd(c,0,1)*100;this.B.params.Km=b;this.B.params.xp=c;this.B.params.Jk=
a;this.B.params.isDefault=!1;this.j.Km=b;this.j.xp=c;this.j.Jk=a;this.j.isDefault=!1;this.qa.Km=b;this.qa.xp=c;this.qa.Jk=a;this.qa.isDefault=!1;this.j2()}};
g.k.a7=function(){g.hp(this.element,"ytp-dragging")};
g.k.j2=function(){this.FC(this.K)};
g.k.getType=function(){return this.type};
g.k.FC=function(a){var b=this.Cb?0:Math.min(this.OY(),this.maxWidth),c=this.MY(),d=this.Cb;if(d){var e=getComputedStyle(this.D.parentNode);e=p3(e.borderLeftWidth)+p3(e.borderRightWidth)+p3(e.paddingLeft)+p3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Ui===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.mm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.GO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Jk*.96+2;h=this.j.Km;switch(h){case 0:case 3:case 6:(d=this.j.Pe.fontSizeIncrement)&&d>0&&this.j.Ui!==2&&this.j.Ui!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.xp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.mm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.GO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ga||this.K.length>b)b=0,this.Ga=!1,this.K=[],this.N=this.Ma=this.Ja=null,g.qe(this.D);for(;b<a.length;b++)nfb(this,a[b])};
g.k.OY=function(){return 0};
g.k.MY=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};pfb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
pfb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var qfb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];q3.prototype.set=function(a){this.type=a};
q3.prototype.get=function(){return this.type};
r3.prototype.clear=function(){this.state=0};
r3.prototype.update=function(){this.state=this.state===2?1:0};
r3.prototype.oe=function(){return this.state!==0};
r3.prototype.matches=function(a,b){return this.oe()&&a===this.Qw&&b===this.Jt};
Mfb.prototype.reset=function(){this.timestamp=this.j=0};
s3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
s3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
s3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Nfb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ofb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Pfb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Qfb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Ufb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
ofb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Yfb.prototype.D=function(){};g.z(x3,g.$C);x3.prototype.toString=function(){return g.$C.prototype.toString.call(this)};g.z(y3,g.O);y3.prototype.gp=function(){return[]};
y3.prototype.reset=function(){};g.z(z3,g.$C);z3.prototype.toString=function(){return g.$C.prototype.toString.call(this)};
var A3=0;g.z(B3,y3);B3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
B3.prototype.gp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=D3(a,"b");
l!=null&&(h.bold=l);l=D3(a,"i");l!=null&&(h.italic=l);l=D3(a,"u");l!=null&&(h.underline=l);l=E3(a,"et");l!=null&&(h.charEdgeStyle=l);l=E3(a,"of");l!=null&&(h.offset=l);l=G3(a,"bc");l!=null&&(h.background=l);l=G3(a,"ec");l!=null&&(h.bP=l);l=G3(a,"fc");l!=null&&(h.color=l);l=E3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=C3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=C3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=C3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=E3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.hg=l>10?l-1:l);a=E3(a,"hg");a!=null&&(h.GZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=bgb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=cgb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=dgb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!D3(m,"a");l=(C3(m,"t")||0)+l;var n=C3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.hg&&(t.hg===1?(t=r.slice(m,
m+4),t.length===4&&(u=$fb(l,n,f,h,p,t,this.pens),m+=3)):u=$fb(l,n,f,h,p,[y],this.pens)),!u){var B=y;u=l;y=n;t=f;var C=h,G=p,H=B.textContent?B.textContent:"",N=B.getAttribute("p");N=N?this.pens[N]:null;B=C3(B,"t")||0;u=new x3(u+B,y-B,G,t,H,C,N)}}else u=new x3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=dgb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Kgb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(H3,y3);H3.prototype.reset=function(){this.B.clear()};
H3.prototype.gp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.bP=I3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=I3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=I3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.hg=h>10?h-1:h,f.tp=Kgb.get(f.hg));e.hgHorizGroup&&(f.GZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.DB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Ui=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.HU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=I3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Jk=e.ahHorPos),e.apPoint!==void 0&&(f.Km=e.apPoint),e.avVerPos!==void 0&&(f.xp=e.avVerPos),e.ccCols!==void 0&&(f.Mt=e.ccCols),e.rcRows!==void 0&&(f.Os=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=egb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+A3++,d=egb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,B=null;t.pPenId&&(B=this.j.get(t.pPenId));if((l.params.DB!=null?l.params.DB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],G;if(G=B&&B.hg===1){G=q;var H=m;if(H+3>=G.length||!G[H+1].pPenId||!G[H+2].pPenId||!G[H+3].pPenId)G=!1;else{var N=G[H+1].pPenId;(N=this.j.get(N))&&N.hg&&N.hg===2?(N=G[H+2].pPenId,N=this.j.get(N),!N||!N.hg||
N.hg<3?G=!1:(N=G[H+3].pPenId,G=(N=this.j.get(N))&&N.hg&&N.hg===2?!0:!1)):G=!1}}if(G)y=q[m+1].utf8,t=q[m+3].utf8,G=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=Zfb(u,y,G,t,H),t=new x3(e,f,p,h,u,n,B),m+=3;else{if(u.indexOf("<")>-1){var M=void 0;C=B;G=r;H=e;N=f;var X=y,W=p,fa=n,pa=[],ba=g.d1("<html>"+u+"</html>");if(!ba.getElementsByTagName("parsererror").length&&((M=ba.firstChild)==null?0:M.childNodes.length))for(M=g.w(ba.firstChild.childNodes),ba=M.next();!ba.done;ba=M.next()){ba=ba.value;var R=void 0,
V=void 0,v=(V=(R=ba.textContent)==null?void 0:R.replace(/\n/g,""))!=null?V:"";if(ba.nodeType!==3||v&&v.match(/^ *$/)==null){R={};Object.assign(R,C||G);V=void 0;switch((V=ba)==null?void 0:V.tagName){case "b":R.bold=!0;break;case "i":R.italic=!0;break;case "u":R.underline=!0}pa.push(new x3(H+X,N-X,W,l.id,v,fa,R))}}C=pa}C.length||(C=[new x3(e+y,f-y,p,l.id,u,n,B||r)])}if(C.length)for(n=g.w(C),B=n.next();!B.done;B=n.next())B=B.value,d.push(B),l.j.push(B);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=
[];return b};g.z(J3,g.ZX);J3.prototype.Lu=function(a,b,c){Teb(this.videoData.videoId,a.vssId,c)};
J3.prototype.qB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.YX(this.B,c.value);a()};g.z(K3,o3);K3.prototype.GO=function(a){var b=this.B.j;o3.prototype.GO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Lgb);var e=c.j;var f=d}nfb(this,c,d)}};
var Lgb={s$:!0};g.z(L3,Yfb);L3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+A3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new z3(c,d-c,5,f,{textAlign:0,Km:0,Jk:b*2.5,xp:a*5.33});e=new x3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(O3,y3);O3.prototype.gp=function(a){a=new L3(a,a.byteLength,this.B);if(fgb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=N3(a)*(1E3/45):a.version===1&&(a.C=N3(a)*4294967296+N3(a)),a.G=M3(a);a.G>0;a.G--){var b=M3(a),c=M3(a),d=M3(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,JX:c,KX:d,order:b.j.length}))}Lfb(this.j,a);return a.B}return[]};
O3.prototype.reset=function(){this.j.clear()};g.z(P3,o3);g.k=P3.prototype;g.k.j2=function(){g.$o(this.Va)};
g.k.tca=function(){g.hp(this.element,"ytp-rollup-mode");this.FC(this.Sb,!0)};
g.k.MY=function(){return this.C?this.oa:this.Y};
g.k.OY=function(){return this.C?this.Y:this.oa};
g.k.FC=function(a,b){this.Sb=a;if(this.B.params.Os){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Hb=this.oa;this.Y=this.oa=0;o3.prototype.FC.call(this,a);jgb(this,b)}o3.prototype.FC.call(this,a)};g.z(Q3,y3);
Q3.prototype.gp=function(a,b){var c=[];a=a.split(Mgb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Ngb.test(e)){var h=Ogb.exec(e);if(h&&h.length>=4){var l=lgb(h[1]),m=lgb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.xp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Jk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Jk=0;break;case 1:h.Jk=100;break;case 2:h.Jk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Km=q}e=e.substring(Ogb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=mgb(l,m,5,t),m=new x3(l,m,5,f.id,h,!1,g.Hc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Pgb),q.length===1?(h=5,t=mgb(l,m,h,t)):(p=h=6,t=Object.assign({Mt:32},t),t=new z3(l,m,p,"_"+A3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.d1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,kgb(this,p,m-(p-l),h,t,r>0,y,e,c)):p=lgb(n)+f}Ogb.lastIndex=0}}return c};
var Ngb=/^NOTE/,Mgb=/(?:\r\n|\r|\n){2,}/,Ogb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Pgb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.b_.ZK(Q3,{gp:"wvppt"});g.z(R3,g.O);
R3.prototype.gp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){a:{var e=d,f=pgb(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.BU;h=typeof p!=="string"?h.concat(qgb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(rgb(this,p,q)):h.concat(tgb(this,b,p,q))}var r=h;break a}catch(t){g.Gw(t);this.clear();r=[];break a}r=void 0}if(r.length!==0)return r}a=ngb(a);if(!a)return[];try{return typeof a!=="string"?qgb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?
rgb(this,a,c):tgb(this,b,a,c)}catch(t){return g.Gw(t),this.clear(),[]}};
R3.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
R3.prototype.reset=function(){this.j&&this.j.reset()};
R3.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var $3={windowColor:"#080808",windowOpacity:0,textAlign:2,Km:7,Jk:50,xp:100,isDefault:!0,Pe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(S3,g.WX);g.k=S3.prototype;g.k.xa=function(){if(this.D||this.Da){var a=this.J.Be();a&&!a.Ka()&&a.aA()}else Jgb(this,!1);g.WX.prototype.xa.call(this)};
g.k.nU=function(){return this.W.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Wa};
g.k.Dv=function(){if(this.Va)return this.D||this.Da;var a=this.getAudioTrack();if(this.nU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Qeb(a,g.bP(this.W));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?T3(this):xgb(this)||T3(this)?!0:ygb(this)};
g.k.load=function(){var a=this;g.WX.prototype.load.call(this);this.Z=this.getAudioTrack();this.j?this.B&&(this.Xa.clear(),this.D?Cgb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Lu(this.B,"json3",function(b,c,d,e){if(b){var f;Egb(a,(f=a.B)!=null?f:void 0);a.j.nT()&&(a.Ga=[],a.J.rf("captions"),l3(a.Ja),a.Xa.reset());if(a.videoData.Dd){var h;d=((h=d)!=null?h:0)+a.videoData.Dd}b=a.Xa.gp(b,c,d,e);if(a.fb)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Zl=a.videoData.Dd;c=!a.W.L("html5_keep_caption_data_after_seek")&&a.Wa;a.player.kf(b,void 0,c);!a.N||a.Da||W3(a)||!a.W.In||g.xC(a.W)||g.OO(a.W)||g.Hy(a.W)||a.W.Ja==="shortspage"||a.player.isInline()||(g.ap(a.Ma),b=agb({Km:0,Jk:5,xp:5,Os:2,textAlign:0,Ui:0,lang:"en"}),a.Qa=[b],c=["Click "," for settings"],a.qb||(e=new g.jx(g.Cx()),g.P(a,e),a.qb=e.element),e=b.end-b.start,(f=g.tP(a.B))&&a.Qa.push(new x3(b.start,e,0,b.id,f)),a.Qa.push(new x3(b.start,e,0,b.id,c[0]),new x3(b.start,e,0,b.id,a.qb,!0),
new x3(b.start,e,0,b.id,c[1],!0)),a.player.kf(a.Qa),g.Zo(a.Ma));!a.N||a.Da||W3(a)||(g.bP(a.W)?Y3(a,!0):Z3(a,!0),a.Z&&(a.Z.D=a.B),a.player.Bp());a.N=!1}}),this.D||this.Da||W3(this)||this.player.yd("captionschanged",g.uP(this.B))):(this.j=zgb(this),g.P(this,this.j),this.j.qB(function(){Bgb(a)}))};
g.k.unload=function(){this.D&&this.B?Cgb(this,!1):(this.Ma&&g.ap(this.Ma),this.player.rf("captions"),this.Ga=[],this.j&&this.j.nt(),this.Xa.clear(),this.Y&&this.player.kf(this.Y),this.UU());g.WX.prototype.unload.call(this);this.player.Bp();this.player.yd("captionschanged",{})};
g.k.create=function(){this.Dv()&&this.load();var a;a:{var b,c,d;if(this.W.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.bda=function(){for(var a=this.J.Be().Jb().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.XX(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&X3(this,b,!0)};
g.k.Afa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ga.push(a);l3(this.Ja)};
g.k.onCueRangeExit=function(a){g.Wb(this.Ga,a);this.j instanceof n3&&this.j.N&&this.player.qp([a]);l3(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.Zda=function(){Igb(this,this.Qa);this.Qa=null};
g.k.TU=function(){var a=this;if(!this.Cb||!this.D){this.Ja.stop();g.iba(this.Ua);this.Ga.sort(g.aD);var b=this.Ga;if(this.Y){var c=g.hn(b,function(f){return this.Y.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())Ggb(this,c.value);b=g.w(Object.entries(this.Ba));var d=b.next();for(c={};!d.done;c={SA:void 0,Vp:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.SA=d;c.Vp=e;this.Ua[c.SA]?(c.Vp.element.parentNode||(c.Vp instanceof P3||c.Vp instanceof K3||g.Ac(this.Ba,function(f){return function(h,l){l!==f.SA&&h.B.params.Km===f.Vp.B.params.Km&&h.B.params.Jk===f.Vp.B.params.Jk&&h.B.params.xp===f.Vp.B.params.xp&&(h.dispose(),delete a.Ba[l]);
return l===f.SA}}(c),this),this.K.element.appendChild(c.Vp.element)),c.Vp.FC(this.Ua[c.SA])):(c.Vp.dispose(),delete this.Ba[c.SA])}}};
g.k.fea=function(){vgb(this,{},!0);this.player.yd("captionssettingschanged")};
g.k.E9=function(){var a=$3.Pe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:$3.windowColor,windowOpacity:$3.windowOpacity};var b=Xeb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.X3=function(a,b){var c={};Object.assign(c,Xeb());Object.assign(c,a);vgb(this,c,b);this.player.yd("captionssettingschanged")};
g.k.UU=function(){!this.D&&this.loaded&&(g.xc(this.Ba,function(a,b){a.dispose();delete this.Ba[b]},this),this.TU())};
g.k.gi=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Hd(b,-2,4);this.X3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&X3(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.W.N&&(g.bP(this.W)?Y3(this,!!b):Z3(this,!!b));break;case "track":if(!this.j)return{};if(b){this.W.L("html5_report_caption_format_intent")&&this.Tj(g.Hc(b)?"":b.vss_id,"m");if(this.D)break;if(!g.Qa(b))break;if(g.Hc(b)){X3(this,null,!0);break}a=g.XX(this.j.B,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.tP(e)!==b.displayName)||(c=b.translationLanguage?Reb(e,b.translationLanguage):e)}this.uN(b.position);!c||c===this.B&&this.loaded||(b=g.cL(),a=g.vP(c),b.length&&a===b[b.length-1]||(b.push(a),g.Gs("yt-player-caption-language-preferences",b)),g.bP(this.W)&&!this.J.isInline()&&g.Gs("yt-player-caption-sticky-language",a,2592E3),X3(this,c,!0))}else return this.loaded&&this.B&&!W3(this)?g.uP(this.B):
{};return"";case "tracklist":return this.j?g.zl(g.XX(this.j.B,!(!b||!b.includeAsr)),function(f){return g.uP(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||Jgb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Jgb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.cL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.N&&a.push("stickyLoading");return a};
g.k.Yr=function(){var a=this.B;if(this.W.L("html5_cue_ranges_based_caption_vss")&&!this.J.MK("captions"))return{};if(this.W.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.aE)!=null?b:null)?{cc:g.sKa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.vP(a)),{cc:b}):{}};
g.k.mfa=function(){this.isSubtitlesOn()?(this.W.L("html5_report_caption_format_intent")&&this.Tj("","m"),g.bP(this.W)?Y3(this,!1):Z3(this,!1),Egb(this),this.W.L("html5_report_caption_format_change")?X3(this,null,!0):(this.unload(),T3(this,!0)&&X3(this,U3(this),!1))):this.y3()};
g.k.y3=function(){if(this.W.L("html5_report_caption_format_intent")){var a=W3(this)||!this.B?V3(this,!0):this.B;this.Tj(a?a.vssId:"","m")}this.isSubtitlesOn()||X3(this,W3(this)||!this.B?V3(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!W3(this)};
g.k.MG=function(){this.j&&this.j.MG()};
g.k.Oaa=function(){var a=W3(this);T3(this,a)?X3(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.nU()&&(this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Dv()&&(a?X3(this,V3(this),!1):this.load()))};
g.k.uN=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=Hgb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.yd("captionschanged",{})),this.Dv()&&this.load())};
g.k.getAudioTrack=function(){return this.fb&&this.player.getPresentingPlayerType()===2?this.videoData.ll:this.player.getAudioTrack()};
g.k.Cba=function(){var a=this.J.Be();a&&!a.Ka()&&a.aA();this.J.isFullscreen()?(this.D=this.Va=!0,this.loaded&&Bgb(this)):(this.Va=this.W.controlsType==="3",this.D=ugb(this));X3(this,this.B)};
g.k.HN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.ib("innertubeCommand",d)};
g.k.pj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"",f=f.replace(d,""));a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.pj(b?e:"",b?f:"",c)};
g.k.Tj=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.Tj(a,b)};
g.b_.ZK(S3,{TU:"smucd"});g.VX("captions",S3);})(_yt_player);
